### ISSUE TITLE
timestamp navigation moves POINT to interior of properties drawers

### ISSUE THREAD

**Issue by Boruch-Baum** [bpanthi977/org-mpv-notes#11]
When the next/previous timestamp is within a property drawer,
functions org-mpv-notes-{next,previous}-timestamp move point to that
location. It should probably move to the first position after the
drawer.

**Comment by bpanthi977** [comment]
Now `org-mpv-notes-next-timestamp` and `org-mpv-notes-previous-timestamp` use `org-next-link` to find links so links insides property drawers are not considered as links.

In previous version of org-mpv-notes while inserting a headline note, the timestamp was kept in property drawer, so this function needed to look in the whole buffer. But since now we ignore timestamp string and only consider mpv: links we can ignore looking inside property drawers.
