### ISSUE TITLE
Add example workflow to readme.org

### ISSUE THREAD

**Issue by tvraman** [bpanthi977/org-mpv-notes#19]
Adding an end-to-end workflow to the Readme.org might make it easier  for new users to put the pieces together. Thank you for  a really nice package, it's really well done!

**Comment by bpanthi977** [comment]
Hi! Thanks for the suggestion.

I have updated the README.org. It is not exactly an end-to-end workflow. But I think it will guide new users better. Would you please give it a read and comment on how it feels?

**Comment by v-Nyo** [comment]
As a complete noob I had no problems at all to set this up. I really love this package! makes it super easy to organize you media (tagging, playlists, notes, learning etc...).

The only issues I had were with empv (maybe you could share how you use and set it up bc it's mainly audio focus).

And I would suggest to link to this page so users can setup a mpv link:
https://github.com/kljohann/mpv.el/wiki#using-org-mode-for-transcription-tested-with-org-mode-version-94

**Comment by bpanthi977** [comment]
Thanks!

I use `mpv` instead of `empv`, so I am a little unaware about the issues empv has. If you can create an issue describing the problem and provide steps to replicate it, I can try solving the issue. 

Regarding the mpv link, org-mpv-notes package already sets it up. But that code is loaded only when the package is loaded. So, you can either do 
```elisp
(use-package org-mpv-notes 
   :defer nil
   ...)
```
Or add an hook to org-mode so that org-mpv-notes is activated by default in org-mode
```elisp
(use-package org
   :hook (org-mode . org-mpv-notes-mode)
   ...)
```

**Comment by bpanthi977** [comment]
> Regarding the mpv link, org-mpv-notes package already sets it up. But that code is loaded only when the package is loaded.

I pushed an update to the package. Now you can do the following:
```elisp
(use-package org-mpv-notes
   :hook (org-mode . org-mpv-notes-setup-link)
   ...
```

The README is also updated accordingly.
